chore: upgrade to latest workflows

diff --git a/.github/workflows/org.container.yml b/.github/workflows/org.container.yml
--- a/.github/workflows/org.container.yml
+++ b/.github/workflows/org.container.yml
@@ -133,8 +133,9 @@ jobs:
       DOCKER_IMAGE_DESCRIPTION: ${{ steps.setup-environment.outputs.DOCKER_IMAGE_DESCRIPTION }}
       DOCKER_IMAGE_NAME_AND_VERSION: ${{ steps.setup-environment.outputs.DOCKER_IMAGE_NAME_AND_VERSION }}
       DOCKER_IMAGE_ARGUMENTS: ${{ steps.setup-environment.outputs.DOCKER_IMAGE_ARGUMENTS }}
+      DOCKER_CICD_LATEST: ${{ steps.setup-environment.outputs.DOCKER_CICD_LATEST }}
       WORKFLOW_BUILD: ${{ steps.setup-environment.outputs.WORKFLOW_BUILD }}
-      WORKFLOW_BUILD_SUCCESS: ${{ steps.build-success.outputs.WORKFLOW_BUILD_SUCCESS }}
+      REGISTRY_QUAY: ${{ steps.setup-environment.outputs.REGISTRY_QUAY }}
 
     timeout-minutes: 1440
 
@@ -165,6 +166,11 @@ jobs:
           ref: ${{ github.ref_name }}
           fetch-depth: 0
 
+      # CHECK IF QUAY.IO IS DOWN AGAIN
+      - name: init / check quay.io
+        run: |
+          echo "QUAY_STATUS=$(curl -s https://status.redhat.com/api/v2/components.json | jq -r '.components[] | select(.name | contains("Quay") or contains("quay")) | .status')" >> $GITHUB_ENV
+
       # SETUP NODE JS
       - name: update / setup node
         uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
@@ -178,7 +184,7 @@ jobs:
         uses: actions/github-script@ed597411d8f924073f98dfc5c65a23a2325f34cd # v8.0.0
         with:
           script: |
-            const { existsSync, readFileSync } = require('node:fs');
+            const { existsSync, readFileSync, writeFileSync } = require('node:fs');
             const { resolve } = require('node:path');
             const { inspect } = require('node:util');
             const { Buffer } = require('node:buffer');
@@ -243,6 +249,11 @@ jobs:
                 registry:'localhost:5000/',
                 enable:(opt.input?.etc?.cache === undefined) ? true : opt.input.etc.cache,
               },
+              registry:{
+                docker:{enabled:true},
+                ghcr:{enabled:true},
+                quay:{enabled:true},
+              },
               tags:[],
               merge_tags:[],
             };
@@ -250,7 +261,7 @@ jobs:
             try{
               // wait 2.5s too not trigger 429 from github
               await new Promise(r => setTimeout(r, 2500));
-              const response = await fetch('https://raw.githubusercontent.com/11notes/static/refs/heads/master/src/semver/latest.json');
+              const response = await fetch('https://raw.githubusercontent.com/11notes/CICD/refs/heads/master/semver/latest.json');
               if(!response.ok){
                 throw new Error(`error fetching global versions: ${response.status}`);
               }
@@ -259,7 +270,7 @@ jobs:
                 const depSemver = semverValid(semverCoerce(result[dep]));
                 docker.app[`${dep}_version`] = `${result[dep]}`;
                 docker.app[`${dep}_major_minor_version`] = `${semverMajor(depSemver)}.${semverMinor(depSemver)}`;
-                docker.app[`${dep}_major_version`] = semverMajor(depSemver);
+                //docker.app[`${dep}_major_version`] = semverMajor(depSemver);
                 core.info(`setting APP_${String(dep).toUpperCase()}_VERSION to ${result[dep]}`);
               }
             }catch(e){
@@ -274,6 +285,12 @@ jobs:
             const semver = (
               (/stable|latest/i.test(docker.app.version)) ? [] : docker.app.version.split('.')
             );
+
+            // setup additional version tags
+            if(semver.length >= 2){
+              docker.app.major_minor_version = `${semver[0]}.${semver[1]}`;
+            }
+
             // setup tags
               if(!opt.dot?.semver?.disable?.rolling && !opt.input.etc?.semver?.disable?.rolling){
                 docker.image.tags.push('rolling');
@@ -294,8 +311,8 @@ jobs:
                   if(semver.length >= 2) docker.image.tags.push(`${semver[0]}.${semver[1]}`);
                   if(semver.length >= 3) docker.image.tags.push(`${semver[0]}.${semver[1]}.${semver[2]}`);
                 }
-                if(opt.dot?.semver?.stable && new RegExp(opt.dot?.semver.stable, 'ig').test(docker.image.tags.join(','))) docker.image.tags.push('stable');
-                if(opt.dot?.semver?.latest && new RegExp(opt.dot?.semver.latest, 'ig').test(docker.image.tags.join(','))) docker.image.tags.push('latest');
+                if(opt.dot?.semver?.stable && new RegExp(opt.dot?.semver.stable, 'ig').test(docker.image.tags.join(',')) || docker.app.version === "stable") docker.image.tags.push('stable');
+                if(opt.dot?.semver?.latest && new RegExp(opt.dot?.semver.latest, 'ig').test(docker.image.tags.join(',')) || docker.app.version === "latest") docker.image.tags.push('latest');
               }else{
                 docker.image.tags.push('latest');
               }
@@ -303,7 +320,12 @@ jobs:
               for(const tag of docker.image.tags){
                 docker.tags.push(`${docker.image.name}:${docker.image.prefix}${tag}${docker.image.suffix}-${docker.image.platform.sanitized}`);
                 docker.tags.push(`ghcr.io/${docker.image.name}:${docker.image.prefix}${tag}${docker.image.suffix}-${docker.image.platform.sanitized}`);
-                docker.tags.push(`quay.io/${docker.image.name}:${docker.image.prefix}${tag}${docker.image.suffix}-${docker.image.platform.sanitized}`);
+                if('${{ env.QUAY_STATUS }}' === 'operational'){
+                  core.setOutput('REGISTRY_QUAY', true);
+                  docker.tags.push(`quay.io/${docker.image.name}:${docker.image.prefix}${tag}${docker.image.suffix}-${docker.image.platform.sanitized}`);
+                }else{
+                  core.setOutput('REGISTRY_QUAY', false);
+                }
                 docker.merge_tags.push(`${docker.image.prefix}${tag}${docker.image.suffix}`);
               }
 
@@ -342,6 +364,9 @@ jobs:
               core.exportVariable('DOCKER_IMAGE_NAME_AND_VERSION', `${docker.image.name}:${docker.app.version}`);
               core.setOutput('DOCKER_IMAGE_NAME_AND_VERSION', `${docker.image.name}:${docker.app.version}`);
 
+              // CI/CD
+              core.setOutput('DOCKER_CICD_LATEST', opt.dot?.CICD?.latest || false);
+
               core.setOutput('DOCKER_IMAGE_TAG_LATEST', (
                 docker.image.tags.includes('latest') ? "true" : "false"
               ));
@@ -368,6 +393,12 @@ jobs:
                       case /11notes\/python\:\$\{APP_PYTHON_VERSION\}/ig.test(file): core.exportVariable('WORKFLOW_IMAGE_DEPENDENCY', 'python'); break;
                       case /11notes\/php\:\$\{APP_PHP_VERSION\}/ig.test(file): core.exportVariable('WORKFLOW_IMAGE_DEPENDENCY', 'php'); break;
                       case /11notes\/php-fpm\:\$\{APP_PHP_VERSION\}/ig.test(file): core.exportVariable('WORKFLOW_IMAGE_DEPENDENCY', 'php'); break;
+                      case /11notes\/dotnetsdk\:\$\{APP_DOTNET8_VERSION\}/ig.test(file): core.exportVariable('WORKFLOW_IMAGE_DEPENDENCY', 'dotnet8'); break;
+                      case /11notes\/dotnetsdk\:\$\{APP_DOTNET9_VERSION\}/ig.test(file): core.exportVariable('WORKFLOW_IMAGE_DEPENDENCY', 'dotnet9'); break;
+                      case /11notes\/dotnetsdk\:\$\{APP_DOTNET10_VERSION\}/ig.test(file): core.exportVariable('WORKFLOW_IMAGE_DEPENDENCY', 'dotnet10'); break;
+                      case /11notes\/dotnetsdk\:\$\{APP_DOTNET11_VERSION\}/ig.test(file): core.exportVariable('WORKFLOW_IMAGE_DEPENDENCY', 'dotnet11'); break;
+                      case /11notes\/node\:\$\{APP_NODE_VERSION\}/ig.test(file): core.exportVariable('WORKFLOW_IMAGE_DEPENDENCY', 'node'); break;
+                      case /11notes\/node\:stable/ig.test(file): core.exportVariable('WORKFLOW_IMAGE_DEPENDENCY', 'node_stable'); break;
                     }
                   }catch(e){
                     throw new Error(`could not open ./${dockerfile}: ${e}`);
@@ -379,6 +410,24 @@ jobs:
                 core.warning(e);
               }
 
+            // export all variables
+              const objectToEnvArray = (o, p = '', a = []) => {
+                for(const k in o){
+                  switch(typeof(o[k])){
+                    case 'object':
+                    case 'array':
+                      objectToEnvArray(o[k], `${p}${k}_`.toUpperCase(), a)
+                      break;
+                    default:
+                      a.push(`${p}${k}`.toUpperCase() + '=' + o[k]);
+                  }
+                }
+                return(a);
+              }
+
+              writeFileSync('${{ runner.temp }}/global.env', objectToEnvArray(opt.dot, 'GLOBAL_JSON_').join('\n') + '\n', {encoding: "utf8", flag: "a+"});
+              writeFileSync('${{ runner.temp }}/global.env', objectToEnvArray(docker, 'GLOBAL_DOCKER_').join('\n') + '\n', {encoding: "utf8", flag: "a+"});
+              writeFileSync('${{ runner.temp }}/global.env', objectToEnvArray(opt.input?.etc, 'GLOBAL_INPUT_ETC_').join('\n') + '\n', {encoding: "utf8", flag: "a+"});
 
             // print
               core.info(inspect({opt:opt, docker:docker}, {showHidden:false, depth:null, colors:true}));
@@ -389,7 +438,7 @@ jobs:
       # ╚═════════════════════════════════════════════════════╝
       # REGISTER WORKFLOW DEPENDENCY ON BASE IMAGE
       - name: register image dependency
-        uses: the-actions-org/workflow-dispatch@3133c5d135c7dbe4be4f9793872b6ef331b53bc7
+        uses: benc-uk/workflow-dispatch@31e2b3319479a63f0ab15bf800eff9e913504e26 #v1.3.2
         if: env.WORKFLOW_IMAGE_DEPENDENCY != '' && matrix.platform == 'amd64'
         with:
           wait-for-completion: false
@@ -465,7 +514,7 @@ jobs:
 
       # SCAN LOCAL CONTAINER IMAGE WITH GRYPE
       - name: container image / scan with grype
-        if: env.WORKFLOW_BUILD == 'true'
+        if: env.WORKFLOW_BUILD == 'true' && matrix.platform == 'amd64'
         id: grype
         uses: anchore/scan-action@e1165082ffb1fe366ebaf02d8526e7c4989ea9d2 # v7.4.0
         with:
@@ -473,20 +522,43 @@ jobs:
           fail-build: ${{ env.WORKFLOW_GRYPE_FAIL_ON_SEVERITY }}
           severity-cutoff: ${{ env.WORKFLOW_GRYPE_SEVERITY_CUTOFF }}
           output-format: 'sarif'
-          by-cve: true
-          cache-db: true
+          output-file: ${{ runner.temp }}/grype.json
 
-      # OUTPUT CVE REPORT IF SCAN FAILS
-      - name: container image / scan with grype FAILED
+      - name: container image / scan with grype FAILED / json output
         if: env.WORKFLOW_BUILD == 'true' && (failure() || steps.grype.outcome == 'failure') && steps.image-build.outcome == 'success'
-        uses: anchore/scan-action@e1165082ffb1fe366ebaf02d8526e7c4989ea9d2 # v7.4.0
-        with:
-          image: ${{ env.DOCKER_CACHE_GRYPE }}
-          fail-build: false
-          severity-cutoff: ${{ env.WORKFLOW_GRYPE_SEVERITY_CUTOFF }}
-          output-format: 'table'
-          by-cve: true
-          cache-db: true
+        run: |
+          cat ${{ runner.temp }}/grype.json | jq -r '.runs[].tool.driver.rules[].help.markdown' >> $GITHUB_STEP_SUMMARY
+
+      # PERFORM INTEGRATION TEST
+      - name: container image / integration test
+        id: integration
+        if: hashFiles('./.github/tests/integration/compose.yml') != ''
+        run: |
+          cd ./.github/tests/integration
+          IMAGE="${{ env.DOCKER_CACHE_GRYPE }}" docker compose up -d
+          echo "waiting for container startup (max 60s) ..."
+          for TRY in $(seq 1 12); do
+            HEALTH=$(docker inspect --format='{{json .State.Health}}' integration-main-1 | jq -r '.Status')
+            echo "container health (#${TRY}): ${HEALTH}"
+            if [ ${HEALTH} == "healthy" ]; then
+              echo "integration test successfull!"
+              exit 0
+            else
+              if [ ${HEALTH} == "unhealthy" ]; then
+                break
+              else
+                sleep 5s
+              fi
+            fi
+          done
+          echo "container integration test failed!!!"
+          echo "container healthcheck logs:"
+          echo "-----------------------------------------------------------------"
+          docker inspect --format='{{json .State.Health}}' integration-main-1 | jq
+          echo "container logs:"
+          echo "-----------------------------------------------------------------"
+          docker logs integration-main-1
+          exit 1
 
       # PUSH IMAGE TO ALL REGISTRIES IF CLEAN
       - name: container image / push to registries
@@ -539,7 +611,7 @@ jobs:
         if: env.WORKFLOW_BUILD == 'true' && steps.image-push.outcome == 'success'
         id: build-success
         run: |
-          echo "WORKFLOW_BUILD_SUCCESS=true" >> $GITHUB_OUTPUT
+          echo "GLOBAL_WORKFLOW_BUILD_SUCCESS=true" >> ${{ runner.temp }}/global.env
 
 
       # ╔═════════════════════════════════════════════════════╗
@@ -564,6 +636,16 @@ jobs:
           draft: false
           prerelease: false
 
+      # ╔═════════════════════════════════════════════════════╗
+      # ║            UPLOAD GLOBAL.ENV ARTIFACT               ║
+      # ╚═════════════════════════════════════════════════════╝
+      - name: github workflow / export environment
+        if: matrix.platform == 'amd64'
+        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
+        with:
+          name: global.env
+          path: ${{ runner.temp }}/global.env
+
 
   # ╔═════════════════════════════════════════════════════╗
   # ║                                                     ║
@@ -580,7 +662,7 @@ jobs:
     strategy:
       fail-fast: false
       matrix:
-        registry: [docker.io, ghcr.io, quay.io]
+        registry: ${{ needs.docker.outputs.REGISTRY_QUAY == 'true' && fromJSON('["docker.io", "ghcr.io"]') || fromJSON('["docker.io", "ghcr.io", "quay.io"]') }}
 
     env:
       DOCKER_IMAGE_NAME: ${{ needs.docker.outputs.DOCKER_IMAGE_NAME }}
@@ -593,6 +675,21 @@ jobs:
       id-token: write
 
     steps:
+      # ╔═════════════════════════════════════════════════════╗
+      # ║               LOAD GLOBAL VARIABLES                 ║
+      # ╚═════════════════════════════════════════════════════╝
+      # LOAD ARTIFACT
+      - name: global variables / load artifact
+        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
+        with:
+          name: global.env
+          path: ${{ runner.temp }}
+
+      # SET ENV
+      - name: global variables / set env
+        run: cat ${{ runner.temp }}/global.env >> $GITHUB_ENV
+
+
       # ╔═════════════════════════════════════════════════════╗
       # ║             CONTAINER REGISTRY LOGIN                ║
       # ╚═════════════════════════════════════════════════════╝
@@ -684,6 +781,20 @@ jobs:
 
     steps:
       # ╔═════════════════════════════════════════════════════╗
+      # ║               LOAD GLOBAL VARIABLES                 ║
+      # ╚═════════════════════════════════════════════════════╝
+      # LOAD ARTIFACT
+      - name: global variables / load artifact
+        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
+        with:
+          name: global.env
+          path: ${{ runner.temp }}
+
+      # SET ENV
+      - name: global variables / set env
+        run: cat ${{ runner.temp }}/global.env >> $GITHUB_ENV
+
+      # ╔═════════════════════════════════════════════════════╗
       # ║                 SETUP ENVIRONMENT                   ║
       # ╚═════════════════════════════════════════════════════╝
       # CHECKOUT ALL DEPTHS (ALL TAGS)
@@ -715,7 +826,7 @@ jobs:
 
       # CREATE MAKRDOWN OF README.md
       - name: README.md / create
-        if: github.event.inputs.readme == 'true' && (needs.docker.outputs.WORKFLOW_BUILD_SUCCESS == 'true' || github.event.inputs.run-name == 'readme')
+        if: github.event.inputs.readme == 'true' && (env.GLOBAL_WORKFLOW_BUILD_SUCCESS == 'true' || github.event.inputs.run-name == 'readme')
         id: github-readme
         continue-on-error: true
         uses: 11notes/action-docker-readme@v1
@@ -790,4 +901,4 @@ jobs:
               "secret":"${{ secrets.DOCKER_TOKEN }}"
             }' \
             --fail | jq -r ".access_token")
-          curl -s -H "Authorization: Bearer ${TOKEN}" -X DELETE https://hub.docker.com/v2/repositories/${{ env.DOCKER_IMAGE_NAME }}/tags/latest | echo ":latest tag not found"
+          curl -s -H "Authorization: Bearer ${TOKEN}" -X DELETE https://hub.docker.com/v2/repositories/${{ env.DOCKER_IMAGE_NAME }}/tags/latest || echo ":latest tag not found"
